title: qtest
description: qtest
template:
  repo: qtest-template
  name: qtest
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: Close this issue
    actions:
      - type: createIssue
        title: Create a Thread Group
        body: new-issue.md
    description: Close this issue to go
    link: '{{ repoUrl }}/issues/1'
    event: issues.closed
